bat/bat

- BAT/BCHistogramBase.h
- examples/advanced/roointerface/runRooInterface.cxx
- models/base/BATCalculator.cxx
- models/base/BCRooInterface.cxx
> Fix roostats interface

- benchmarks/PerfTestSuite/Makefile
- benchmarks/PerfTestSuite/include/TestSuite.h
- benchmarks/PerfTestSuite/runTestSuite.cxx
- benchmarks/PerfTestSuite/src/PerfTest1DFunction.cxx
- benchmarks/PerfTestSuite/src/PerfTest2DFunction.cxx
- benchmarks/PerfTestSuite/src/PerfTestMCMC.cxx
- benchmarks/PerfTestSuite/src/ReleaseTestSuite.cxx
- benchmarks/PerfTestSuite/src/TestSuite.cxx
- src/BCEngineMCMC.cxx
> Performance test suite overhauled to be useful again

- BAT/BCEngineMCMC.h
- src/BCEngineMCMC.cxx
- test/GaussModel.cxx
- test/GaussModel.h
- test/parallel_TEST.cxx
> fix parallel test

- BAT/BCEngineMCMC.h
- examples/advanced/polynomialFit/PolAsymm.h
- examples/basic/histogramFitter/histogramFitterExample.C
- models/base/BCEfficiencyFitter.cxx
- models/base/BCEfficiencyFitter.h
- models/base/BCFitter.cxx
- models/base/BCFitter.h
- models/base/BCGraphFitter.cxx
- models/base/BCGraphFitter.h
- models/base/BCHistogramFitter.cxx
- src/BCEngineMCMC.cxx
- test/parallel_TEST.cxx
fix seg faults in examples deriving from `BCFitter` mentioned in #72
> bug fix initialization

- configure.ac
> [configure] build cuba with `make lib`

- examples/basic/rootOutput/Makefile.am
- examples/basic/rootOutput/readRootOutput.cxx
> Fix `make check` in rootOutput example

- BAT/BCDataPoint.h
- BAT/BCDataSet.h
- BAT/BCEngineMCMC.h
- BAT/BCLog.h
- configure.ac
- examples/basic/histogramFitter/histogramFitterExample.C
- models/base/BCEfficiencyFitter.cxx
- models/base/BCFitter.cxx
- models/base/BCGraphFitter.cxx
- models/base/BCGraphFitter.h
- models/base/BCHistogramFitter.cxx
- src/BCDataPoint.cxx
- src/BCDataSet.cxx
- src/BCEngineMCMC.cxx
- src/BCLog.cxx
- src/BCModel.cxx
- src/BCPriorModel.cxx
Main motivation, see discussion #81.
I also fixed the p value calculation in `BCGraphFitter`. `BCEfficiencyFitter` still seems broken, see #80
> Fix fast fitter with multiple threads

- .gitignore
- autogen.sh
- test/Makefile.am
> Fix remaining autoreconf warnings

- BAT/BCIntegrate.h
- src/BCIntegrate.cxx
* replace vegas by divonne for cuba
* allow grid up to 3d
* count #calls to posterior in grid
* prefer cuba if it is available
see #79 for discussion on whether to accept this pull request
> [BCIntegrate] Change default behavior for integration

- BAT/BCEngineMCMC.h
- src/BCEngineMCMC.cxx
- test/BCEngineMCMC_TEST.cxx
I found a bug in the multivariate proposal and fixed it. Together with @greenwald I reviewed the default settings and updated them. `make distcheck` on root 6.04.10 passes
> Refine MCMC settings

- src/BCEngineMCMC.cxx
- src/BCHistogramBase.cxx
This employs some minor fixes to clean up a few drawing issues. Address issue #93
> Fixes to drawing functions

- BAT/BCAux.h
- BAT/BCEngineMCMC.h
- BAT/BCIntegrate.h
- benchmarks/PerfTestSuite/include/PerfTestMCMC.h
- benchmarks/PerfTestSuite/setup.sh
- benchmarks/PerfTestSuite/src/PerfTest2DFunction.cxx
- benchmarks/PerfTestSuite/src/PerfTestMCMC.cxx
- benchmarks/PerfTestSuite/src/TestSuite.cxx
- examples/advanced/advancedGraphFitter/graphFitterAdvancedExample.C
- models/base/BCFitter.cxx
- models/base/BCGraphFitter.cxx
- models/base/BCRooInterface.cxx
- models/mtf/BCMTF.cxx
- models/mtf/BCMTFAnalysisFacility.cxx
- models/mtf/BCMTFComparisonTool.cxx
- models/mtf/BCMTFComparisonTool.h
- src/BCEngineMCMC.cxx
- src/BCIntegrate.cxx
- test/BCEngineMCMC_TEST.cxx
- test/BCIntegrate_TEST.cxx
- test/IntegrationModel.h
- test/Makefile.am
- test/parallel_TEST.cxx
* fix cuba in 1D #99 and integration test #118
* remove last todo tags from code and convert them into github issues or fix them right away #116 
* fix bug in multivariate proposal with fixed parameters
* fix a compiler warning
> Integration & marginalization

- configure.ac
- doc/Doxyfile
- examples/Makefile-common.am
- examples/advanced/rooInterface/Makefile.am
- examples/advanced/rooInterface/README
- examples/advanced/rooInterface/runBATCalculator.C
- examples/advanced/rooInterface/runRooInterface.cxx
- models/base/BATCalculator.cxx
- models/base/BATCalculator.h
- models/base/BCRooInterface.cxx
- models/base/BCRooInterface.h
- src/BCEngineMCMC.cxx
- src/BCVariable.cxx
- tools/build/root.m4
refactor and reactivate examples. Fixes #100
> Roointerface, BATCalculator

- examples/basic/rootOutput/readRootOutput.cxx
- models/base/BCEfficiencyFitter.cxx
Addresses issues #129 and #130.
> Drawing fixes

- tools/Main1Template.cxx
- tools/MakefileTemplate.in
- tools/ModelTemplate.cxx
- tools/ModelTemplate.h
Addresses issue #139 
Also cleans up some of the comments and adds an example of `CalculateObservables`
> Cleaned up templates used by bat-project

- BAT/BCIntegrate.h
- src/BCEngineMCMC.cxx
- src/BCIntegrate.cxx
- src/BCParameterSet.cxx
- test/BCIntegrate_TEST.cxx
- test/BCModel_TEST.cxx
- test/GaussModel.cxx
- test/GaussModel.h
fixes #160 and some other bugs I found along the way relateded to fixing parameters.
> update minuit interface and add Laplace approximation

- src/BCEngineMCMC.cxx
Until now the multivariate proposal function was ignoring the user-set scale. This fixes that.
> [BCEngineMCMC] multivariate proposal function usesfMCMCInitialScaleFactors

- src/BCModel.cxx
Fixes recursion bug in swap(BCModel, BCModel)
> [BCModel] fix bug in swap

- tools/ModelTemplate.cxx
changing incorrect `BCPriorGaus` to correct `BCGaussianPrior`
> fix bug in commented out code of template source

- BAT/BCTH1Prior.h
- src/BCTH1Prior.cxx
- test/BCPrior_TEST.cxx
fixes #174 
I had to convert to a pointer thanks to root limitations. Awesome! Please don't merge yet as more changes from #191 might come about
> [BCTH1Prior] Copy input histogram

- .travis.yml
This adds CentOS-7 with ROOT-5 to the test matrix
> Improve travis-ci integration

- src/BCVariableSet.cxx
- src/Makefile.am
fixes #198 . I tested it on Ubuntu 16.04 with root 6.09.02.
> Fix cling payload errors

- src/BCParameter.cxx
- test/BCEngineMCMC_TEST.cxx
> [BCParameter] Fix parameter if given with zero range

- src/BCHistogramBase.cxx
One line fix to the plotting issue. Simple change, difficult find!
> Fixing bug of issue #213

- src/BCMath.cxx
> [BCMath] Handle zero expectation in LogPoisson

- BAT/BCMath.h
- INSTALL.md
- configure.ac
- models/mtf/BCMTF.cxx
- models/mtf/BCMTFChannel.cxx
- models/mtf/BCMTFChannel.h
- src/BCIntegrate.cxx
- src/BCMath.cxx
In this PR, I want to address several of the issues flagged as bugs. To start, I tried to build BAT on an old system and ran into surprising problems. Then I got the latest compiler I could get my hands on (gcc7.3) and it reported a few warnings with `configure --enable-debug CXXFLAGS='-Werror' 
More to come but I post this now to invite comments already on the current status and to see that everything passes on travis
> Bug closing

- BAT/BCLog.h
- src/BCEngineMCMC.cxx
- src/BCLog.cxx
> Log results

- BAT/BCModel.h
- src/BCEngineMCMC.cxx
> More robust tree initialization

- BAT/BCAux.h
- BAT/BCEngineMCMC.h
- models/base/BCFitter.h
- src/BCAux.cxx
- src/BCEngineMCMC.cxx
- src/BCModel.cxx
- tools/test-bat.sh
> Engine trash

- BAT/BCIntegrate.h
- models/base/BATCalculator.cxx
- src/BCEngineMCMC.cxx
- src/BCMath.cxx
- tools/test-bat.sh
Fixes #259 and a few small things along the way
> Mode output

- src/BCAux.cxx
The previous fix did not solve the same issue in plotting of knowledge update plots. This pull request addresses that.
> [wip] Further fix to issue #213

- models/base/BCFitter.h
> [fitter] Document all methods

- configure.ac
- tools/build/ax_openmp.m4
Fixes #265 
I couldn't actually test on a mac as reported by @gipert but I checked that it works with a compliant compiler and fails with a clear error message if openmp is not available.
> [configure] Check for OpenMP

- src/Makefile.am
> [src] Update ROOT header order

- configure.ac
> [configure] Set U flag for cuba archive generation

- BAT/BCEngineMCMC.h
- BAT/BCParameter.h
- examples/.gitignore
- examples/basic/rootOutput/Makefile.am
- examples/basic/rootOutput/README
- examples/basic/rootOutput/continueMCMC.cxx
- examples/basic/rootOutput/readRootOutput.cxx
- models/base/BCEfficiencyFitter.cxx
- src/BCAux.cxx
- src/BCConstantPrior.cxx
- src/BCDataSet.cxx
- src/BCEngineMCMC.cxx
- src/BCH1D.cxx
- src/BCHistogramBase.cxx
- src/BCIntegrate.cxx
- src/BCMath.cxx
- src/BCModelManager.cxx
- src/BCParameter.cxx
- src/BCParameterSet.cxx
- src/BCPrior.cxx
- src/BCSplitGaussianPrior.cxx
- src/BCVariable.cxx
- test/BCModel_TEST.cxx
One can now continue chains from information stored in the BAT ROOT output.
> Continue chains from info in a file

- models/base/BATCalculator.cxx
Fixes issue in https://github.com/bat/bat/pull/301#issuecomment-390121730
> Roostats guard

- models/base/BATCalculator.cxx
- src/BCEngineMCMC.cxx
- src/BCIntegrate.cxx
- test/BCPrior_TEST.cxx
> Format code with astyle

- src/BCModelManager.cxx
> fixing fDataSet = NULL bug

- BAT/BCModelManager.h
- src/BCModelManager.cxx
Give access to model comparison info (prior and posterior)
> Access model mgr results
