bat/bat

Makefile.am

If they are formatted with astyle, subsequent builds fail on my machine

[format] Exclude *rdict.cxx from formatting

---

INSTALL.md
configure.ac

fixes #76
* configure doesn't fail if roostats is unavailable but reports whether
it is used
* bump min. root version to 5.27/04. This is what we claimed roostats
requires. I haven't tested this. In any case that is outdated
* update install instructions, including clang's missing support for openmp
Note: All my available root versions have roostats so I checked that things work fine if it's not available by removing the feature `roofit` from `root-config`.

[configure,install] Enable roostats by default

---

BAT/BCEngineMCMC.h
BAT/BCH1D.h
BAT/BCMath.h
benchmarks/PerfTestSuite/Makefile
benchmarks/PerfTestSuite/include/PerfTest.h
benchmarks/PerfTestSuite/include/PerfTest1DFunction.h
benchmarks/PerfTestSuite/include/PerfTest2DFunction.h
benchmarks/PerfTestSuite/include/PerfTestMCMC.h
benchmarks/PerfTestSuite/include/PerfTestVarPar.h
benchmarks/PerfTestSuite/include/ReleaseTestSuite.h
benchmarks/PerfTestSuite/include/TestSuite.h
benchmarks/PerfTestSuite/runTestSuite.cxx
benchmarks/PerfTestSuite/src/PerfTest1DFunction.cxx
benchmarks/PerfTestSuite/src/PerfTest2DFunction.cxx
benchmarks/PerfTestSuite/src/PerfTestMCMC.cxx
benchmarks/PerfTestSuite/src/PerfTestVarPar.cxx
benchmarks/PerfTestSuite/src/ReleaseTestSuite.cxx
benchmarks/PerfTestSuite/src/TestSuite.cxx
configure.ac
src/BCEngineMCMC.cxx
src/BCH1D.cxx
src/BCIntegrate.cxx
src/BCMath.cxx
test/BCEngineMCMC_TEST.cxx
test/BCIntegrate_TEST.cxx
test/GaussModel.cxx
test/GaussModel.h
test/Makefile.am
test/parallel_TEST.cxx

The main goal was to implement #31. It requires random numbers from the chi2 distribution. I implemented two alternatives. The much faster way is to use the GSL via MathMore. If that is not available, I use the inverse transform. The quantile function is slow, at least in root.
Along the way, I
* fixed the performance test suite (#17) that I checked to work with factorized and multivariate proposal, both serial and parallel extending #32
* fixed some memory bugs in the core reported by valgrind
* reduced the memory allocation during MCMC #63
I hope this is the last major new feature of the code for 1.0

Multivariate student's t proposal

---

src/BCModel.cxx

We currently calculate the LogLikelihood (often expensive), then calculate the LogPrior (often cheap). It makes more sense to first calculate the LogPrior; if this returns an invalid (not finite) value, the LogLikelihood is not evaluated, and is set simply to -infinity. (We could also have NaN, if prefered.)

[BCModel] Check logPrior before calculating logLikelihood

---

BAT/BCEngineMCMC.h
examples/advanced/polynomialFit/PolAsymm.h
models/base/BCFitter.cxx
models/base/BCFitter.h
src/BCEngineMCMC.cxx

Now errors can't be ignored anymore and the chain doesn't run, avoiding hard-to-find segfaults.
Resolves #91

[BCEngine] MCMC[User]Initialize() throws exceptions

---

src/BCMath.cxx

[BCMath] Separate errors in LogPoisson for lambda == 0 and lambda < 0

---

src/BCHistogramBase.cxx

In case of an open TFile during instance creation, the TFile is the owner of the stored histogram, this is fixed by SetDirectory(0)

fixed issue with root directory ownership

---

tools/ModelTemplate.cxx

There's a bug in the implementation file of the template. Minor bugfix here.

fix bug in return value of implementation of CalculateObservables

---

src/BCConstantPrior.cxx

fixes bug in which random point is generated currently by: `min + rand * max`; instead of by: `min + rand * (max - min)`

[BCConstantPrior] fixes bug in getting random point according to prior.

---

BAT/BCEngineMCMC.h
src/BCEngineMCMC.cxx

Added a member variable, `fInitialPositionAttemptLimit`, to `BCEngineMCMC` to control the maximum number of attempts to make to initialize the Markov chains. Added the requisite getter and setter. Upped the default value to 100 (from the previous 10).

[BCEngineMCMC] +fInitialPositionAttemptLimit

---

models/base/BCFitter.cxx
models/base/BCFitter.h

Added the possibility to extend the errorband in Y and X range to cover cases in which the needed x or y range is higher than	 the default errorband range. One Example could be a calibration which has to be evaluated beyond the highest x point.
Added a function which returns a copy of the internal errorband histogram. In this case one could store it for later usage.

Added errorband related function to BCFitter

---

examples/.gitignore
src/BCIntegrate.cxx
src/BCLog.cxx

If a parameter like
```
BCParameter a("a", 0., 1.);
a.Fix(0.);
```
is added in BAT, using `FindModeMinuit` will return a result in which this parameter no longer is zero. Currently BAT adds a limited variable to Minuit for each parameter, and then fixes this variable to its value if the parameter is fixed. But Minuit (at least the version used by BAT) does not allow a variable at one of its limits, but instead always moves the variable into its fit range. Fixing the variable then fixes it to the shifted value. The fix is to add a fixed variable from the beginning.
Add additional watchers: @pdigiglio

Fix for fixed parameters in Minuit

---

test/BCIntegrate_TEST.cxx

Please add this test in addition to #199 to make sure things work in the future as well

[BCIntegrate_TEST] fix par at edge of allowed range

---

configure.ac

Fixes error if autoconf and libtool are not installed in the default
location
configure.ac:8: warning: macro 'AM_PROG_LIBTOOL' not found in library
configure.ac:8: error: possibly undefined macro: AM_PROG_LIBTOOL
If this token and others are legitimate, please use m4_pattern_allow.
See the Autoconf documentation.

[configure.ac] Add m4/ directory for libtool macros

---

examples/advanced/advancedGraphFitter/graphFitterAdvancedExample.C
examples/advanced/mtf/ensembleTest/ensembleTest.C
examples/advanced/mtf/mcstat/mcstat.C
examples/advanced/mtf/singleChannel/singleChannel.C
examples/advanced/mtf/twoChannels/twoChannels.C
examples/basic/efficiencyFitter/efficiencyFitterExample.C
examples/basic/graphFitter/graphFitterSimpleExample.C
examples/basic/histogramFitter/histogramFitterExample.C

Motivated by #208, I updated the root macros to not rely on undefined behavior of macro expansion report by clang 3.8

[examples] Fix clang 3.8 undefined macro behavior

---

models/base/Makefile.am
models/mtf/Makefile.am

#195 broke linking of ROOT libs (ROOStats in particular) on some
platforms (e.g. Ubuntu Linux).

[build] Fix broken linking of ROOT libs

---

INSTALL.md
configure.ac
examples/basic/histogramFitter/histogramFitterExample.C
models/base/BCEfficiencyFitter.cxx
models/base/BCFitter.cxx
models/base/BCFitter.h
models/base/BCHistogramFitter.cxx
models/base/BCHistogramFitter.h
tools/test-bat.sh

This PR 
* bumps the minimum root version to 5.34.19 (so the `TH1::Copy` function is available)
* convert the mixture of tabs and spaces in `configure.ac` to spaces
* fixes #143 by taking into account the bin volume when drawing a graph
* modifies the histFitter example to allow changing values more easily following the DRY principle

Hist fitter

---

src/BCEngineMCMC.cxx

1. Commented out fOut->Write in WriteMarginalizedDistributions which
creates multiple copies of the tree in the root file when used with
writechains. Does not affect the behavior of the member.
2. The histograms in CreateHistograms are not printed with the parameter
name instead of their index. The same for the observables. Everything is
done with the SafeName.
Fixes #169

[engine] More robust marginal output

---

examples/basic/efficiencyFitter/efficiencyFitterExample.C
models/base/BCEfficiencyFitter.cxx
models/base/BCEfficiencyFitter.h
models/base/BCFitter.cxx

Fixes issue #233 .
However, I have a segfault when I run the example `efficiencyFitterExample.C` that stems from the final command `hef.PrintAllMarginalized("distributions.pdf")`.
@fredRos, can you please check if you get this same segfault (also with my updated code in this PR)?

Fixed drawing in BCEfficiencyFitter

---

README.md

I registered BAT with zenodo and uploaded the last release 0.9.4.1 Now we can set this up so for every new release on github a DOI is automatically created
I also fixed the license: in the readme it said GPLv3 but `doc/LICENSE` is actually LGPLv3. Now we have a badge for that, too

[readme] add license+DOI badge. Fix license name

---

BAT/BCEngineMCMC.h
BAT/BCVariableSet.h
models/base/BCRooInterface.cxx
models/mtf/BCMTF.cxx
src/BCEngineMCMC.cxx
src/BCIntegrate.cxx
src/BCLog.cxx
src/BCModel.cxx
test/BCMath_TEST.cxx
test/Makefile.am
test/parallel_TEST.cxx

This addresses #182 and #205 
I have removed storage of the prior during calculation, since it can be reconstructed via (probability - likelihood). However, we don't even need to store it in the `TTree` as a branch. It could be replaced by an alias---which gets saved with the `TTree`. This has the advantage of lightening the footprint of the tree, but the disadvantage that the alias cannot be loaded into a variable the same way a branch can (via `SetBranchAddress`). It will make no difference for a user who draws directly from the `TTree`, but it will make a difference to someone who accesses it through a macro.
I have not been able to fix #205. But have found that the mismatch is not from the prior. It's actually from the likelihood. `LogProbability` agrees with parameter values stored …

Fix thread-safety issues

---

BAT/BCH1D.h
src/BCH1D.cxx
src/BCHistogramBase.cxx
test/BCHistogram_TEST.cxx
test/Makefile.am
test/README.md

Fixes #172, #241 
I did not implement the change [here](https://github.com/talismanbrandi/bat/commit/0613d16b6697d34f86357edd7fc3bd02172d57ce) (`>=` to `>`) because I don't see why we **shouldn't** allow bins that are also equal to the lower bound.

Smallest Interval bug fixes

---

examples/advanced/polynomialFit/PolAsymm.cxx
examples/advanced/polynomialFit/PolAsymm.h

I checked for compiler warnings with different compilers with
./configure --disable-static --enable-debug --enable-silent-rules --with-cuba=download --enable-roostats CXX=clang++-3.8
With this commit, I get no more warnings with ROOT6. Same result with g++7.2. Only  with ROOT5, there are warnings for every BAT library but we won't fix that, it's ROOT internal
```
CXX      libBATmodels_rdict.lo
libBATmodels_rdict.cxx:11:9: warning: keyword is hidden by macro definition [-Wkeyword-macro]
^
libBATmodels_rdict.cxx:12:9: warning: keyword is hidden by macro definition [-Wkeyword-macro]
^
In file included from libBATmodels_rdict.cxx:17:
In file included from ./libBATmodels_rdict.h:18:
/usr/include/root/G__ci.h:968:9: warning: keyword is hidden by macro definition [-Wkeyword-macro]
^
3 warnings …
```

[polynomialFit] Fix clang warning

---

BAT/BCEngineMCMC.h
examples/basic/rootOutput/runRootOutput.cxx
src/BCEngineMCMC.cxx
test/BCModel_TEST.cxx

This implements two ways to continue running chains:
1. Calling `MarginalizeAll()` (or `Metropolis()`) a second (or third, etc) time.
2. Loading in a BAT-generated `.root` file instead of running the prerun, and then continuing chains from there.

Continue running a marginalization in current session

---

INSTALL.md
test/BCModel_TEST.cxx
test/parallel_TEST.cxx
tools/build/ax_openmp.m4

Fixes #286 and #285 
@greenwald  please test that this works on your system with an old version of autoconf

[install, tools] Reduce minimal ax_openmp autoconf version to 2.59

---

configure.ac

This reverts commit b181c39916fe3fc1235dfb3f01c00fdd52a8e444.
The U flag removed ignorable warnings with newer `ar` versions but leads to an
error with old `ar` versions that don't know this flag yet. From a user `configure.log`
```
/nfs/mnemosyne/sys/slc6/contrib/gcc/4.9.1/bin/gcc -std=gnu11 -fPIC -O3 -fomit-frame-pointer -ffast-math -Wall -DHAVE_CONFIG_H -DREALSIZE=8 -I./src/common -I. -I. -I./src/vegas -DNOUNDERSCORE -c -o Vegas.o ./src/vegas/Vegas.c
ar rvU libcuba.a Vegas.o
ar: illegal option -- U
Usage: ar [emulation options] [-]{dmpqrstx}[abcfilNoPsSuvV] [member-name] [count] archive-file file...
ar -M [<mri-script]
commands:
d            - delete file(s) from the archive
m[ab]        - move file(s) in the archive
p            - print file(s) found in the archive
q[f]         - …
```

Revert "[configure] Set U flag for cuba archive generation"

---

src/BCAux.cxx

Replace deprecated `std::ptr_fun` with lambda function. Makes BAT compilable with `-std=c++17` on my Mac.

Fix compilation with C++17 (Clang) #325

---

BAT/BCModelManager.h

1. Defaulted prior for a model to 1. This allows one to add multiple models, all with equal weight, without specifying the weights as they are added. This allows for more expandable code that uses `BCModelManager`.
2. Give access to the vector of `BCModel`'s stored in the manager.

Improvements to BCModelManager

---

BAT/BCModelManager.h
src/BCHistogramBase.cxx
src/BCModelManager.cxx

Addresses #338.
Removes resizing completely since it seems entirely unnecessary.

BCHistogramBase resize bugfix
